[project]
name = "quantum-instructor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beeai-framework>=0.1.32",
    "mcp>=1.12.2",
    "termcolor>=3.1.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
